package py.gov.set.seguimientoControles.pojos;
// Generated 12/09/2017 09:21:01 AM by Hibernate Tools 4.3.1



/**
 * AplicacionesPerfiles generated by hbm2java
 */
public class AplicacionesPerfiles  implements java.io.Serializable {


     private int idAppPerf;
     private Aplicaciones aplicaciones;
     private Perfiles perfiles;
     private Character modifica;

    public AplicacionesPerfiles() {
    }

	
    public AplicacionesPerfiles(int idAppPerf) {
        this.idAppPerf = idAppPerf;
    }
    public AplicacionesPerfiles(int idAppPerf, Aplicaciones aplicaciones, Perfiles perfiles, Character modifica) {
       this.idAppPerf = idAppPerf;
       this.aplicaciones = aplicaciones;
       this.perfiles = perfiles;
       this.modifica = modifica;
    }
   
    public int getIdAppPerf() {
        return this.idAppPerf;
    }
    
    public void setIdAppPerf(int idAppPerf) {
        this.idAppPerf = idAppPerf;
    }
    public Aplicaciones getAplicaciones() {
        return this.aplicaciones;
    }
    
    public void setAplicaciones(Aplicaciones aplicaciones) {
        this.aplicaciones = aplicaciones;
    }
    public Perfiles getPerfiles() {
        return this.perfiles;
    }
    
    public void setPerfiles(Perfiles perfiles) {
        this.perfiles = perfiles;
    }
    public Character getModifica() {
        return this.modifica;
    }
    
    public void setModifica(Character modifica) {
        this.modifica = modifica;
    }




}


