package py.gov.set.seguimientoControles.pojos;
// Generated 12/09/2017 09:21:01 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Aplicaciones generated by hbm2java
 */
public class Aplicaciones  implements java.io.Serializable {


     private int idAplicacion;
     private String descripcion;
     private String padre;
     private String url;
     private Set aplicacionesPerfileses = new HashSet(0);

    public Aplicaciones() {
    }

	
    public Aplicaciones(int idAplicacion) {
        this.idAplicacion = idAplicacion;
    }
    public Aplicaciones(int idAplicacion, String descripcion, String padre, String url, Set aplicacionesPerfileses) {
       this.idAplicacion = idAplicacion;
       this.descripcion = descripcion;
       this.padre = padre;
       this.url = url;
       this.aplicacionesPerfileses = aplicacionesPerfileses;
    }
   
    public int getIdAplicacion() {
        return this.idAplicacion;
    }
    
    public void setIdAplicacion(int idAplicacion) {
        this.idAplicacion = idAplicacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getPadre() {
        return this.padre;
    }
    
    public void setPadre(String padre) {
        this.padre = padre;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Set getAplicacionesPerfileses() {
        return this.aplicacionesPerfileses;
    }
    
    public void setAplicacionesPerfileses(Set aplicacionesPerfileses) {
        this.aplicacionesPerfileses = aplicacionesPerfileses;
    }




}


