package py.gov.set.seguimientoControles.pojos;
// Generated 12/09/2017 09:21:01 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DptoOperativo generated by hbm2java
 */
public class DptoOperativo  implements java.io.Serializable {


     private int idDpto;
     private String nombre;
     private String sigla;
     private Set funcionarioses = new HashSet(0);
     private Set procesoCabeceras = new HashSet(0);

    public DptoOperativo() {
    }

	
    public DptoOperativo(int idDpto) {
        this.idDpto = idDpto;
    }
    public DptoOperativo(int idDpto, String nombre, String sigla, Set funcionarioses, Set procesoCabeceras) {
       this.idDpto = idDpto;
       this.nombre = nombre;
       this.sigla = sigla;
       this.funcionarioses = funcionarioses;
       this.procesoCabeceras = procesoCabeceras;
    }
   
    public int getIdDpto() {
        return this.idDpto;
    }
    
    public void setIdDpto(int idDpto) {
        this.idDpto = idDpto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getSigla() {
        return this.sigla;
    }
    
    public void setSigla(String sigla) {
        this.sigla = sigla;
    }
    public Set getFuncionarioses() {
        return this.funcionarioses;
    }
    
    public void setFuncionarioses(Set funcionarioses) {
        this.funcionarioses = funcionarioses;
    }
    public Set getProcesoCabeceras() {
        return this.procesoCabeceras;
    }
    
    public void setProcesoCabeceras(Set procesoCabeceras) {
        this.procesoCabeceras = procesoCabeceras;
    }




}


