package py.gov.set.seguimientoControles.pojos;
// Generated 12/09/2017 09:21:01 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Feriados generated by hbm2java
 */
public class Feriados  implements java.io.Serializable {


     private Date fecha;
     private Usuarios usuarios;

    public Feriados() {
    }

	
    public Feriados(Date fecha) {
        this.fecha = fecha;
    }
    public Feriados(Date fecha, Usuarios usuarios) {
       this.fecha = fecha;
       this.usuarios = usuarios;
    }
   
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }




}


