package py.gov.set.seguimientoControles.pojos;
// Generated 12/09/2017 09:21:01 AM by Hibernate Tools 4.3.1



/**
 * FuncionariosId generated by hbm2java
 */
public class FuncionariosId  implements java.io.Serializable {


     private int nroDocumento;
     private int dpto;

    public FuncionariosId() {
    }

    public FuncionariosId(int nroDocumento, int dpto) {
       this.nroDocumento = nroDocumento;
       this.dpto = dpto;
    }
   
    public int getNroDocumento() {
        return this.nroDocumento;
    }
    
    public void setNroDocumento(int nroDocumento) {
        this.nroDocumento = nroDocumento;
    }
    public int getDpto() {
        return this.dpto;
    }
    
    public void setDpto(int dpto) {
        this.dpto = dpto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FuncionariosId) ) return false;
		 FuncionariosId castOther = ( FuncionariosId ) other; 
         
		 return (this.getNroDocumento()==castOther.getNroDocumento())
 && (this.getDpto()==castOther.getDpto());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNroDocumento();
         result = 37 * result + this.getDpto();
         return result;
   }   


}


