package py.gov.set.seguimientoControles.pojos;
// Generated 12/09/2017 09:21:01 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Obligaciones generated by hbm2java
 */
public class Obligaciones  implements java.io.Serializable {


     private BigDecimal codObligacion;
     private String nomObligacion;
     private String sigla;
     private String periodicidad;

    public Obligaciones() {
    }

	
    public Obligaciones(BigDecimal codObligacion) {
        this.codObligacion = codObligacion;
    }
    public Obligaciones(BigDecimal codObligacion, String nomObligacion, String sigla) {
       this.codObligacion = codObligacion;
       this.nomObligacion = nomObligacion;
       this.sigla = sigla;
    }
   
    public BigDecimal getCodObligacion() {
        return this.codObligacion;
    }
    
    public void setCodObligacion(BigDecimal codObligacion) {
        this.codObligacion = codObligacion;
    }
    public String getNomObligacion() {
        return this.nomObligacion;
    }
    
    public void setNomObligacion(String nomObligacion) {
        this.nomObligacion = nomObligacion;
    }
    public String getSigla() {
        return this.sigla;
    }
    
    public void setSigla(String sigla) {
        this.sigla = sigla;
    }

    public String getPeriodicidad() {
        return periodicidad;
    }

    public void setPeriodicidad(String periodicidad) {
        this.periodicidad = periodicidad;
    }




}


