package py.gov.set.seguimientoControles.pojos;
// Generated 12/09/2017 09:21:01 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Perfiles generated by hbm2java
 */
public class Perfiles  implements java.io.Serializable {


     private int idPerfil;
     private String descripcion;
     private Character activo;
     private Set usuarioPerfils = new HashSet(0);
     private Set aplicacionesPerfileses = new HashSet(0);

    public Perfiles() {
    }

	
    public Perfiles(int idPerfil) {
        this.idPerfil = idPerfil;
    }
    public Perfiles(int idPerfil, String descripcion, Character activo, Set usuarioPerfils, Set aplicacionesPerfileses) {
       this.idPerfil = idPerfil;
       this.descripcion = descripcion;
       this.activo = activo;
       this.usuarioPerfils = usuarioPerfils;
       this.aplicacionesPerfileses = aplicacionesPerfileses;
    }
   
    public int getIdPerfil() {
        return this.idPerfil;
    }
    
    public void setIdPerfil(int idPerfil) {
        this.idPerfil = idPerfil;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Character getActivo() {
        return this.activo;
    }
    
    public void setActivo(Character activo) {
        this.activo = activo;
    }
    public Set getUsuarioPerfils() {
        return this.usuarioPerfils;
    }
    
    public void setUsuarioPerfils(Set usuarioPerfils) {
        this.usuarioPerfils = usuarioPerfils;
    }
    public Set getAplicacionesPerfileses() {
        return this.aplicacionesPerfileses;
    }
    
    public void setAplicacionesPerfileses(Set aplicacionesPerfileses) {
        this.aplicacionesPerfileses = aplicacionesPerfileses;
    }




}


