package py.gov.set.seguimientoControles.pojos;
// Generated 12/09/2017 09:21:01 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProcesoCabecera generated by hbm2java
 */
public class ProcesoCabecera  implements java.io.Serializable {


     private int nroProceso;
     private DptoOperativo dptoOperativo;
     private TipoControl tipoControl;
     private String ruc;
     private String razonSocial;
     private String origen;
     private String fuente;
     private String nroOrden;
     private Date fechaAsignacion;
     private Date fechaNotificacion;
     private Date fechaFin;
     private Date fechaInforme;
     private String codPlan;
     private String estadoProceso;
     private String resultadoProceso;
     private Set procesoActuanteses = new HashSet(0);
     private Set procesoPeriodoses = new HashSet(0);
     private Set procesoDeterminados = new HashSet(0);
     private Set suspensionProcesoses = new HashSet(0);

    public ProcesoCabecera() {
    }

	
    public ProcesoCabecera(int nroProceso, TipoControl tipoControl, String ruc, String razonSocial) {
        this.nroProceso = nroProceso;
        this.tipoControl = tipoControl;
        this.ruc = ruc;
        this.razonSocial = razonSocial;
    }
    public ProcesoCabecera(int nroProceso, DptoOperativo dptoOperativo, TipoControl tipoControl, String ruc, String razonSocial, String origen, String fuente, String nroOrden, Date fechaAsignacion, Date fechaNotificacion, Date fechaFin, Date fechaInforme, String codPlan, String estadoProceso, String resultadoProceso, Set procesoActuanteses, Set procesoPeriodoses, Set procesoDeterminados, Set suspensionProcesoses) {
       this.nroProceso = nroProceso;
       this.dptoOperativo = dptoOperativo;
       this.tipoControl = tipoControl;
       this.ruc = ruc;
       this.razonSocial = razonSocial;
       this.origen = origen;
       this.fuente = fuente;
       this.nroOrden = nroOrden;
       this.fechaAsignacion = fechaAsignacion;
       this.fechaNotificacion = fechaNotificacion;
       this.fechaFin = fechaFin;
       this.fechaInforme = fechaInforme;
       this.codPlan = codPlan;
       this.estadoProceso = estadoProceso;
       this.resultadoProceso = resultadoProceso;
       this.procesoActuanteses = procesoActuanteses;
       this.procesoPeriodoses = procesoPeriodoses;
       this.procesoDeterminados = procesoDeterminados;
       this.suspensionProcesoses = suspensionProcesoses;
    }
   
    public int getNroProceso() {
        return this.nroProceso;
    }
    
    public void setNroProceso(int nroProceso) {
        this.nroProceso = nroProceso;
    }
    public DptoOperativo getDptoOperativo() {
        return this.dptoOperativo;
    }
    
    public void setDptoOperativo(DptoOperativo dptoOperativo) {
        this.dptoOperativo = dptoOperativo;
    }
    public TipoControl getTipoControl() {
        return this.tipoControl;
    }
    
    public void setTipoControl(TipoControl tipoControl) {
        this.tipoControl = tipoControl;
    }
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public String getOrigen() {
        return this.origen;
    }
    
    public void setOrigen(String origen) {
        this.origen = origen;
    }
    public String getFuente() {
        return this.fuente;
    }
    
    public void setFuente(String fuente) {
        this.fuente = fuente;
    }
    public String getNroOrden() {
        return this.nroOrden;
    }
    
    public void setNroOrden(String nroOrden) {
        this.nroOrden = nroOrden;
    }
    public Date getFechaAsignacion() {
        return this.fechaAsignacion;
    }
    
    public void setFechaAsignacion(Date fechaAsignacion) {
        this.fechaAsignacion = fechaAsignacion;
    }
    public Date getFechaNotificacion() {
        return this.fechaNotificacion;
    }
    
    public void setFechaNotificacion(Date fechaNotificacion) {
        this.fechaNotificacion = fechaNotificacion;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public Date getFechaInforme() {
        return this.fechaInforme;
    }
    
    public void setFechaInforme(Date fechaInforme) {
        this.fechaInforme = fechaInforme;
    }
    public String getCodPlan() {
        return this.codPlan;
    }
    
    public void setCodPlan(String codPlan) {
        this.codPlan = codPlan;
    }
    public String getEstadoProceso() {
        return this.estadoProceso;
    }
    
    public void setEstadoProceso(String estadoProceso) {
        this.estadoProceso = estadoProceso;
    }
    public String getResultadoProceso() {
        return this.resultadoProceso;
    }
    
    public void setResultadoProceso(String resultadoProceso) {
        this.resultadoProceso = resultadoProceso;
    }
    public Set getProcesoActuanteses() {
        return this.procesoActuanteses;
    }
    
    public void setProcesoActuanteses(Set procesoActuanteses) {
        this.procesoActuanteses = procesoActuanteses;
    }
    public Set getProcesoPeriodoses() {
        return this.procesoPeriodoses;
    }
    
    public void setProcesoPeriodoses(Set procesoPeriodoses) {
        this.procesoPeriodoses = procesoPeriodoses;
    }
    public Set getProcesoDeterminados() {
        return this.procesoDeterminados;
    }
    
    public void setProcesoDeterminados(Set procesoDeterminados) {
        this.procesoDeterminados = procesoDeterminados;
    }
    public Set getSuspensionProcesoses() {
        return this.suspensionProcesoses;
    }
    
    public void setSuspensionProcesoses(Set suspensionProcesoses) {
        this.suspensionProcesoses = suspensionProcesoses;
    }




}


