package py.gov.set.seguimientoControles.pojos;
// Generated 12/09/2017 09:21:01 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ProcesoPeriodos generated by hbm2java
 */
public class ProcesoPeriodos  implements java.io.Serializable {


     private int idProcesoPeriodo;
     private ProcesoCabecera procesoCabecera;
     private Integer codObligacion;
     private String obligacion;
     private Date periodoFiscal;

    public ProcesoPeriodos() {
    }

	
    public ProcesoPeriodos(int idProcesoPeriodo, ProcesoCabecera procesoCabecera) {
        this.idProcesoPeriodo = idProcesoPeriodo;
        this.procesoCabecera = procesoCabecera;
    }
    public ProcesoPeriodos(int idProcesoPeriodo, ProcesoCabecera procesoCabecera, Integer codObligacion, String obligacion, Date periodoFiscal) {
       this.idProcesoPeriodo = idProcesoPeriodo;
       this.procesoCabecera = procesoCabecera;
       this.codObligacion = codObligacion;
       this.obligacion = obligacion;
       this.periodoFiscal = periodoFiscal;
    }
   
    public int getIdProcesoPeriodo() {
        return this.idProcesoPeriodo;
    }
    
    public void setIdProcesoPeriodo(int idProcesoPeriodo) {
        this.idProcesoPeriodo = idProcesoPeriodo;
    }
    public ProcesoCabecera getProcesoCabecera() {
        return this.procesoCabecera;
    }
    
    public void setProcesoCabecera(ProcesoCabecera procesoCabecera) {
        this.procesoCabecera = procesoCabecera;
    }
    public Integer getCodObligacion() {
        return this.codObligacion;
    }
    
    public void setCodObligacion(Integer codObligacion) {
        this.codObligacion = codObligacion;
    }
    public String getObligacion() {
        return this.obligacion;
    }
    
    public void setObligacion(String obligacion) {
        this.obligacion = obligacion;
    }
    public Date getPeriodoFiscal() {
        return this.periodoFiscal;
    }
    
    public void setPeriodoFiscal(Date periodoFiscal) {
        this.periodoFiscal = periodoFiscal;
    }




}


