package py.gov.set.seguimientoControles.pojos;
// Generated 12/09/2017 09:21:01 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ProcesoDeterminado generated by hbm2java
 */
public class ProcesoDeterminado  implements java.io.Serializable {


     private int idDeterminacion;
     private ProcesoCabecera procesoCabecera;
     private Integer codObligacion;
     private Date periodoFiscal;
     private Integer montoImponible;
     private Integer impuestoDefraudado;
     private Integer impuestoRecuperado;
     private Integer impuestoPagar;
     private Integer porcMulta;
     private Integer multa;

    public ProcesoDeterminado() {
    }

	
    public ProcesoDeterminado(int idDeterminacion) {
        this.idDeterminacion = idDeterminacion;
    }
    public ProcesoDeterminado(int idDeterminacion, ProcesoCabecera procesoCabecera, Integer codObligacion, Date periodoFiscal, Integer montoImponible, Integer impuestoDefraudado, Integer impuestoRecuperado, Integer impuestoPagar, Integer porcMulta, Integer multa) {
       this.idDeterminacion = idDeterminacion;
       this.procesoCabecera = procesoCabecera;
       this.codObligacion = codObligacion;
       this.periodoFiscal = periodoFiscal;
       this.montoImponible = montoImponible;
       this.impuestoDefraudado = impuestoDefraudado;
       this.impuestoRecuperado = impuestoRecuperado;
       this.impuestoPagar = impuestoPagar;
       this.porcMulta = porcMulta;
       this.multa = multa;
    }
   
    public int getIdDeterminacion() {
        return this.idDeterminacion;
    }
    
    public void setIdDeterminacion(int idDeterminacion) {
        this.idDeterminacion = idDeterminacion;
    }
    public ProcesoCabecera getProcesoCabecera() {
        return this.procesoCabecera;
    }
    
    public void setProcesoCabecera(ProcesoCabecera procesoCabecera) {
        this.procesoCabecera = procesoCabecera;
    }
    public Integer getCodObligacion() {
        return this.codObligacion;
    }
    
    public void setCodObligacion(Integer codObligacion) {
        this.codObligacion = codObligacion;
    }
    public Date getPeriodoFiscal() {
        return this.periodoFiscal;
    }
    
    public void setPeriodoFiscal(Date periodoFiscal) {
        this.periodoFiscal = periodoFiscal;
    }
    public Integer getMontoImponible() {
        return this.montoImponible;
    }
    
    public void setMontoImponible(Integer montoImponible) {
        this.montoImponible = montoImponible;
    }
    public Integer getImpuestoDefraudado() {
        return this.impuestoDefraudado;
    }
    
    public void setImpuestoDefraudado(Integer impuestoDefraudado) {
        this.impuestoDefraudado = impuestoDefraudado;
    }
    public Integer getImpuestoRecuperado() {
        return this.impuestoRecuperado;
    }
    
    public void setImpuestoRecuperado(Integer impuestoRecuperado) {
        this.impuestoRecuperado = impuestoRecuperado;
    }
    public Integer getImpuestoPagar() {
        return this.impuestoPagar;
    }
    
    public void setImpuestoPagar(Integer impuestoPagar) {
        this.impuestoPagar = impuestoPagar;
    }
    public Integer getPorcMulta() {
        return this.porcMulta;
    }
    
    public void setPorcMulta(Integer porcMulta) {
        this.porcMulta = porcMulta;
    }
    public Integer getMulta() {
        return this.multa;
    }
    
    public void setMulta(Integer multa) {
        this.multa = multa;
    }




}


