package py.gov.set.seguimientoControles.pojos;
// Generated 12/09/2017 09:21:01 AM by Hibernate Tools 4.3.1



/**
 * Ruc generated by hbm2java
 */
public class Ruc  implements java.io.Serializable {


     private String ruc;
     private String razonsocial;
     private String categoria;

    public Ruc() {
    }

	
    public Ruc(String ruc) {
        this.ruc = ruc;
    }
    public Ruc(String ruc, String razonsocial, String categoria) {
       this.ruc = ruc;
       this.razonsocial = razonsocial;
       this.categoria = categoria;
    }
   
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }
    public String getRazonsocial() {
        return this.razonsocial;
    }
    
    public void setRazonsocial(String razonsocial) {
        this.razonsocial = razonsocial;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }




}


