package py.gov.set.seguimientoControles.pojos;
// Generated 12/09/2017 09:21:01 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoControl generated by hbm2java
 */
public class TipoControl  implements java.io.Serializable {


     private int idTipo;
     private String descripcion;
     private Integer plazoDias;
     private Character diasHabiles;
     private Set procesoCabeceras = new HashSet(0);

    public TipoControl() {
    }

	
    public TipoControl(int idTipo) {
        this.idTipo = idTipo;
    }
    public TipoControl(int idTipo, String descripcion, Integer plazoDias, Character diasHabiles, Set procesoCabeceras) {
       this.idTipo = idTipo;
       this.descripcion = descripcion;
       this.plazoDias = plazoDias;
       this.diasHabiles = diasHabiles;
       this.procesoCabeceras = procesoCabeceras;
    }
   
    public int getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(int idTipo) {
        this.idTipo = idTipo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getPlazoDias() {
        return this.plazoDias;
    }
    
    public void setPlazoDias(Integer plazoDias) {
        this.plazoDias = plazoDias;
    }
    public Character getDiasHabiles() {
        return this.diasHabiles;
    }
    
    public void setDiasHabiles(Character diasHabiles) {
        this.diasHabiles = diasHabiles;
    }
    public Set getProcesoCabeceras() {
        return this.procesoCabeceras;
    }
    
    public void setProcesoCabeceras(Set procesoCabeceras) {
        this.procesoCabeceras = procesoCabeceras;
    }




}


