package py.gov.set.seguimientoControles.pojos;
// Generated 12/09/2017 09:21:01 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private String idUsuario;
     private Integer nroDocumento;
     private String pass;
     private String activo;
     private Set feriadoses = new HashSet(0);
     private Set usuarioPerfils = new HashSet(0);

    public Usuarios() {
    }

	
    public Usuarios(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Usuarios(String idUsuario, Integer nroDocumento, String pass, String activo, Set feriadoses, Set usuarioPerfils) {
       this.idUsuario = idUsuario;
       this.nroDocumento = nroDocumento;
       this.pass = pass;
       this.activo = activo;
       this.feriadoses = feriadoses;
       this.usuarioPerfils = usuarioPerfils;
    }
   
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Integer getNroDocumento() {
        return this.nroDocumento;
    }
    
    public void setNroDocumento(Integer nroDocumento) {
        this.nroDocumento = nroDocumento;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getActivo() {
        return this.activo;
    }
    
    public void setActivo(String activo) {
        this.activo = activo;
    }
    public Set getFeriadoses() {
        return this.feriadoses;
    }
    
    public void setFeriadoses(Set feriadoses) {
        this.feriadoses = feriadoses;
    }
    public Set getUsuarioPerfils() {
        return this.usuarioPerfils;
    }
    
    public void setUsuarioPerfils(Set usuarioPerfils) {
        this.usuarioPerfils = usuarioPerfils;
    }




}


